||staff@staff.com 
 14:32:43 You entered an invalid id. Please enter a valid id
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\dashboard\UI\order_ui\order.py", line 26, in pay_bill
    raise Exception(err_msg.invalid_id)
Exception: You entered an invalid id. Please enter a valid id
||staff@staff.com 
 14:50:03 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You entered an invalid item name. Please enter a valid item name
||staff@staff.com 
 14:51:53 5
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You chose an invalid option. Please choose a valid option
||staff@staff.com 
 14:52:16 abcderflkjsdf
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You chose an invalid option. Please choose a valid option
||auth time 
 14:57:03 staff@staff
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You enterd an invalid email. Please enter a valid email
||auth time 
 14:57:17 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You chose an invalid option. Please choose a valid option
||auth time 
 14:58:09 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid name. Please enter a valid name
||auth time 
 14:58:17 Invalid name. Please enter a valid name
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\controllers\user_controller\update_profile.py", line 18, in update_name
    raise Exception(err_msg.invalid_name)
Exception: Invalid name. Please enter a valid name
||staff@staff.com 
 15:21:07 get_available_table() missing 2 required positional arguments: 'time_slot' and 'persons'
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\controllers\auth_controller\auth.py", line 78, in user_login
    dashboard()
  File "D:\Indixpert-restaurant-management-\src\dashboard\manage_dashboard.py", line 18, in dashboard
    staff_dashboard()
  File "D:\Indixpert-restaurant-management-\src\dashboard\staff_dashboard.py", line 51, in staff_dashboard
    reservation_page()
  File "D:\Indixpert-restaurant-management-\src\dashboard\UI\pages\reservation_page.py", line 50, in reservation_page
    get_available_table()
TypeError: get_available_table() missing 2 required positional arguments: 'time_slot' and 'persons'
||staff@staff.com 
 15:22:18 Invalid number of person. Please enter a valid number
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\controllers\reservation_controller\reservation.py", line 151, in get_available_table
    raise Exception(err_msg.invalid_number_of_person)
Exception: Invalid number of person. Please enter a valid number
||staff@staff.com 
 15:24:19 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You chose an invalid option. Please choose a valid option
||staff@staff.com 
 15:28:22 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You chose an invalid option. Please choose a valid option
||staff@staff.com 
 15:49:52 abc
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You entered an invalid quantity. Please enter a valid quantity
||staff@staff.com 
 15:57:33 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You chose an invalid option. Please choose a valid option
||staff@staff.com 
 15:59:07 888888
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid mobile number. Please enter a valid mobile number
||staff@staff.com 
 16:05:05 11-11-2024
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date. Please enter a valid date
||staff@staff.com 
 16:05:19 11-11-2024
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date. Please enter a valid date
||staff@staff.com 
 16:05:23 Invalid date. Please enter a valid date
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\controllers\order_controller\order_report.py", line 17, in get_order_by_date
    raise Exception(err_msg.invalid_date)
Exception: Invalid date. Please enter a valid date
||staff@staff.com 
 16:09:00 01-13-2024
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date of birth. Please enter a valid date of birth
||staff@staff.com 
 16:09:43 01-12-1600
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date of birth. Please enter a valid date of birth
||admin@admin.com 
 16:22:38 11-11-2024
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date. Please enter a valid date
||admin@admin.com 
 16:26:39 11-11-2024
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date. Please enter a valid date
||admin@admin.com 
 17:22:39 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date. Please enter a valid date
||admin@admin.com 
 17:22:47 1-1-1
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid date. Please enter a valid date
||admin@admin.com 
 17:26:40 jdsf
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: Invalid mobile number. Please enter a valid mobile number
||staff@staff.com 
 17:32:27 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You entered an invalid item name. Please enter a valid item name
||staff@staff.com 
 17:35:58 
Traceback (most recent call last):
  File "D:\Indixpert-restaurant-management-\src\utility\get_input.py", line 14, in get_input
    raise Exception(err_msg)
Exception: You entered an invalid item name. Please enter a valid item name
